### PR TITLE
Implement streaks counter for users #70

### PR DESCRIPTION
**Pull request by BlazeDex**
# Description

1. The user starts with a streak by logging into the app.
2. If the user does not log in for a day, they will lose their streak.
3. The streak update is applied even if you are logged in.
4. The path to see the user's streaks must be general, without IDs.

## Screenshots

Captura desde 2024-04-24 19-44-18

### CODE REVIEW

**Review by juperameza — CHANGES_REQUESTED** [review]
Code seems fine but lets look at this from a ux persepective. 
This feature implies that you need to actively log in ergo input your user and passwd or clicking a button for google login 
This is at least for me and i belive many more users somewhat of a let down of the app if im trying to log my workout I dont want to log in i want my  credentials to be there already
Maybe try to make the streaks based on if the user recorded a workout 
Let me know what you think tho !!

**Comment by BlazeDex** [comment]
But it works just as you mention. Even if the session is active, the streak is recorded if a day has already passed. We did the test in the afternoon right after you logged in. Likewise, we can show you the functionality in Discord.

**Comment by BlazeDex** [comment]
> Code seems fine but lets look at this from a ux persepective. This feature implies that you need to actively log in ergo input your user and passwd or clicking a button for google login This is at least for me and i belive many more users somewhat of a let down of the app if im trying to log my workout I dont want to log in i want my credentials to be there already Maybe try to make the streaks based on if the user recorded a workout Let me know what you think tho !!


But it works just as you mention. Even if the session is active, the streak is recorded if a day has already passed. We did the test in the afternoon right after you logged in. We can show you the functionality in Discord.

**Review by PudinDeveloper — APPROVED** [review]
I am gonna approve this PR, but I agree with @juperameza. I will take a deeper look tomorrow.

**Review by MauricioNC — APPROVED** [review]

**Review by angel23v — APPROVED** [review]

**Review by juperameza — APPROVED** [review]

**Pull request merged**
